apiVersion: v1
kind: ConfigMap
metadata:
  name: traccar
data:
  traccar-config: |
    <?xml version='1.0' encoding='UTF-8'?>
    <!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>
    <properties>
        <entry key='config.default'>./conf/default.xml</entry>
        <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
        <entry key='database.url'>jdbc:mysql://{host}:{port}/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
        <entry key='database.user'>{username}</entry>
        <entry key='database.password'>{pasword}</entry>
    </properties>
