apiVersion: v1
kind: Service
metadata:
  name: traccar
  namespace: default
  labels:
    app: "traccar"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
    name: web-portal
  - port: 5055
    protocol: TCP
    targetPort: 5055
    name: osmand
  selector:
    app: traccar
  type: "LoadBalancer"
  loadBalancerIP: ""
